[project]
name = "cutom-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.1.1",
    "numpy>=2.3.3",
    "tiktoken>=0.11.0",
    "torch>=2.8.0",
]
